### ISSUE TITLE
Update evaluation script to take one of the valid evaluation files 

### ISSUE THREAD

**Issue by lauralorenz** [ayota/ddl_nlp#53]
We've been using a "fake" evaluation file for our evaluation task since we merged it in for the purposes of testing evaluation workflow, not accuracy. Now that we have a more normal-sized corpus, we should switch out to a real evaluation file and see how we do.

It seems there are 3 options for valid evaluation files:
- https://github.com/ayota/ddl_nlp/blob/71077ba5836ce025c95d8a5457c86c09625f6850/data/evaluation/UMNSRS_similarity_evalfile.csv (@ayota recently posted this so the current thinking is this is the right one)
- https://github.com/ayota/ddl_nlp/blob/71077ba5836ce025c95d8a5457c86c09625f6850/data/evaluation/UMLS_synonyms/MiniMayoSRS.csv
- https://github.com/ayota/ddl_nlp/blob/71077ba5836ce025c95d8a5457c86c09625f6850/data/evaluation/UMLS_synonyms/UMNSRS_similarity.csv (which seems to be similar to the first one in naming and data, but is in a different order so it's hard to tell)

Right now the file used during evaluation testing is [hardcoded into the evaluation script](https://github.com/ayota/ddl_nlp/blob/71077ba5836ce025c95d8a5457c86c09625f6850/fun_3000/evaluation/similarity_evaluation.py#L19) but should probably be configurable. We should choose whichever one we want to use, set it as our default configuration in the Drakefile, and refactor evaluation to take the configured similarity file as the test set.

**Comment by ayota** [comment]
I am working on adding the opts to the eval file, but to start I added some stuff to the [readme](https://github.com/ayota/ddl_nlp/blob/53_add_eval_params/README.md#step-4-evaluation) to try to explain what is going on with all the new parameters and the eval files. 

My thoughts on the many files is as follows:

**Keep** ❤️ 
1. `UMNSRS_similarity_evalfile.csv`
2. `MiniMayoSRS.csv`

**Delete** :wastebasket: 
1. `new_medical_similarity.csv` -- because it's only 30ish terms so it is not realistic for an eval file for our needs; and it has some formatting issues (kidney failure and renal failure are each two terms instead of one)
2. `UMNSRS_similarity.csv` -- because it's a dupe
3. `fake_response.csv` -- because we know everything works now, and it is confusing

**Comment by lauralorenz** [comment]
Hey took a look at the readme and dug into the script a bit too. This is actually my first time looking through evaluation and I'm pretty confused actually lol.

Questions
1) Why do we generate folds in the first place (pre word2vec) to generate k word2vec models? I'm wondering if the score averaging system used here to produce a single metric even makes sense. 
2) This whole evaluation script seems like it should be way less fractured as its pretty procedural. What was the purpose of the thin OO wrapper around functional programming gone wild? :dancing_men: 
3) Are there references about why we chose this model to fit this task?

**Comment by lauralorenz** [comment]
Re https://github.com/ayota/ddl_nlp/issues/53#issuecomment-256539964 we're scrapping the whole thing because we don't want to do evaluation this way. #67 will cleanse the evaluation script and we can start over. Closing this issue.
